### ISSUE TITLE
Can't install on python 3.5

### ISSUE THREAD

**Issue by d9k** [jaysonsantos/jinja-assets-compressor#30]
Hello!
Thanks for providing awesome package!
I've upgraded to kubuntu 16.04 and it have python 3 version 3.5 by default.
But jac is dependant on `rjsmin==1.0.10` which causes an error during installation `Need at max python 3.4 (vs. 3.5.1)`.
Newer version of rjsmin support python 3.5 (see https://github.com/ndparker/rjsmin/issues/5)
So please fix dependancy problem.

**Comment by jaysonsantos** [comment]
@d9k Could you test it again?

**Comment by jaysonsantos** [comment]
I forgot to say, 0.14.2 version is uploaded.

**Comment by d9k** [comment]
@jaysonsantos, thanks, it works, but how can release `0.14.2` come after `0.15.0`?

**Comment by jaysonsantos** [comment]
@d9k I didn't see before that Alan had incremented it and as it is not something new and it does not break the current API I incremented only the patch level.

**Comment by jaysonsantos** [comment]
Now I saw the problem, I made a mistake 0.15.0 was already there. I will change it and release 0.15.1.

**Comment by alanhamlett** [comment]
Oops, sorry about that. I thought my fork was up-to-date.
