### ISSUE TITLE
offline_compress not work with macro

### ISSUE THREAD

**Issue by lewis617** [jaysonsantos/jinja-assets-compressor#33]
offline_compress not work with macro, e.g:

```python
{% import 'home/circle.html' as circle with context %}
{% set js = circle.js() %}
    {% compress 'js' %}
        {{ js }}
    {% endcompress %}
```
 this wont generate the compressed js file

please fix this bug,thanks

**Comment by alanhamlett** [comment]
There isn't really a point... look at how django-compressor makes you define any variables inside compress blocks in your settings file:
http://django-compressor.readthedocs.io/en/latest/usage/#offline-compression

Loading your JS into a template variable is the wrong way to use jinja-assets-compressor.

**Comment by lewis617** [comment]
thanks, I will find better way to handle this.

**Comment by alanhamlett** [comment]
The way I pass variables to JS from templates is by defining them in a `script` tag just above my `{% compress 'js' %}` block:

```html
<script>
window.current_user_id = '{{ current_user_id }}';
</script>
{% compress 'js' %}
<script src="{{ STATIC_URL }}js/page.js" >
{% endcompress %}
```
