### ISSUE TITLE
how to deploy on multi servers with this tools?

### ISSUE THREAD

**Issue by lewis617** [jaysonsantos/jinja-assets-compressor#34]
I use this tools on multi servers, and it generates 404 error because there are different compressed js file between different servers.

So  I want ask, how to deploy on multi servers with this tools?

**Comment by jaysonsantos** [comment]
Did you execute offline compression on all servers? https://github.com/jaysonsantos/jinja-assets-compressor/blob/48ae914a896d5f1ea0c94ddcfc76e2d927090905/README.md#offline-compression

**Comment by lewis617** [comment]
I will try this way, thanks
