### ISSUE TITLE
This tool is too slow, how to improve？

### ISSUE THREAD

**Issue by lewis617** [jaysonsantos/jinja-assets-compressor#46]

**Comment by alanhamlett** [comment]
Dev or prod?

**Comment by lewis617** [comment]
Dev

**Comment by alanhamlett** [comment]
Once #47 is merged and a new version released, let me know if the performance is better.

**Comment by lewis617** [comment]
Ok, Hope to be better.

**Comment by alanhamlett** [comment]
New version is ready to try: 0.16

**Comment by lewis617** [comment]
New version is faster than before, thanks!

**Comment by alanhamlett** [comment]
Another performance improvement, but only for offline compression: #65
