### ISSUE TITLE
Dependencies shouldn't be pinned

### ISSUE THREAD

**Issue by diogobaeder** [jaysonsantos/jinja-assets-compressor#54]
Hi,

Since this is a library, the dependencies for it shouldn't be pinned - if there are known incompatibilities, the versions should be set to ranges (like `>=1.1,<2`, if it's incompatible with versions 2 and above from a certain library) and not exact versions. Otherwise, projects which use this library won't be able to use other versions from these dependencies.

E.g.: I have a project which uses a newer version of `six`, but since `jac` pins it to an older version, I can't use that, it's conflicting.

Thanks!

**Comment by jaysonsantos** [comment]
Thanks @diogobaeder this will be fixed in #55

**Comment by diogobaeder** [comment]
Thanks Jayson! Good job! :-)

Hey, if I may suggest something else: if I were you, I would pin dependencies in requirements for specific versions that are used when testing and developing, to make sure the library behavior is reproducible under specific conditions, but leave them open (no version specified, or maybe use a range of versions to ensure enough flexibility) inside `setup.py`, so that projects that depend on that library don't need to use those specific versions.

This way, you can be sure more similarity between the development environments for people who develop the library with you, but also enable the library to be flexible enough to be included as a dependency in other projects.

It's only a suggestion, though. The main issue I created here is fixed, as far as I'm concerned.

Cheers! And great library, by the way! :-)

**Comment by jaysonsantos** [comment]
@diogobaeder , the project is a bit stopped but when I find some time I will do it and also I would like to put tox and make travis play with it to make local development easier for the multiple python versions.
