### ISSUE TITLE
Allow configuring compiler commands

### ISSUE THREAD

**Issue by alanhamlett** [jaysonsantos/jinja-assets-compressor#7]
For changing compiler programs and their arguments.

Follow the django-compressor convention of mime-type to compiler command which is passed to str.format()

    COMPILERS = (
        # ('text/coffeescript', 'coffee --compile --stdio'),
        # ('text/less', 'lessc {infile} {outfile}'),
        # ('text/x-sass', 'sass {infile} {outfile}'),
        # ('text/stylus', 'stylus < {infile} > {outfile}'),
        # ('text/x-scss', 'sass --scss {infile} {outfile}'),
    )

**Comment by urbaniak** [comment]
:+1:

My additional wish is an option to pass a class/function (instead of a string/shell command) to use for example libsass-python.

@jaysonsantos, are you willing to merge feature like that?

I can work on it and do a pull request if it's possible to merge it upstream.

**Comment by jaysonsantos** [comment]
@urbaniak Sure!
